with-expecter: true
inpackage: false
dir: "mocks"
packages:
  github.com/bacalhau-project/andaime/pkg/interfaces:
    config:
      all: true
  github.com/bacalhau-project/andaime/pkg/providers/aws:
    config:
      all: true
      recursive: true
  github.com/bacalhau-project/andaime/pkg/providers/azure:
    config:
      all: true
      recursive: true
  github.com/bacalhau-project/andaime/pkg/providers/gcp:
    config:
      all: true
      recursive: true
  github.com/bacalhau-project/andaime/pkg/providers/common:
    config:
      all: true
      recursive: true
