with-expecter: true
inpackage: false
with-imports: true
keyed-interfaces: true
packages:
  github.com/bacalhau-project/andaime/pkg/models/interfaces/aws/types:
    config:
      dir: mocks/aws/types
      outpkg: types
      filename: "mock_{{.InterfaceName}}.go"
      all: true
      recursive: true
      keyed-interfaces: true
    interfaces:
      EC2Client:
      STSClient:
      EC2Operations:
      VPCOperations:
      NetworkOperations:
      GatewayOperations:
      RouteOperations:
      RegionOperations:
      IMDSClient:
  github.com/bacalhau-project/andaime/pkg/models/interfaces/aws:
    config:
      dir: mocks/aws
      outpkg: aws
      filename: "mock_{{.InterfaceName}}.go"
      all: true
      recursive: true
      keyed-interfaces: true
    interfaces:
      EC2Clienter:
      EC2BaseOperations:
      EC2ContextOperations:
      RunInstancesAPI:
      DescribeInstancesAPI:
      TerminateInstancesAPI:
      ImageAPI:
      VPCAPI:
      SubnetAPI:
      SecurityGroupAPI:
      InternetGatewayAPI:
      RouteTableAPI:
      RegionAPI:
      STSClienter:
  github.com/bacalhau-project/andaime/pkg/models/interfaces/sshutils:
    config:
      dir: mocks/sshutils
      outpkg: sshutils
      filename: "mock_{{.InterfaceName}}.go"
      all: true
      recursive: true
      keyed-interfaces: true
    interfaces:
      SSHSessioner:
      SSHClienter:
      SSHClientCreator:
      SFTPClienter:
      SFTPClientCreator:
