azure:
  allowed_ports:
    - 22
    - 80
    - 443
  default_count_per_zone: 1
  default_disk_size_gb: 30
  default_location: eastus
  default_machine_type: Standard_DS1_v2
  default_vm_size: Standard_B2s
  disk_size_gb: 30
  machines:
    - location: eastus
      parameters:
        count: 2
        type: Standard_DS1_v2
    - location: centralus
      parameters:
        count: 1
        orchestrator: true
        type: Standard_DS1_v2
    - location: eastus2
  resource_group_location: eastus
  resource_group_name: andaime-rg
  resource_prefix: andaime
  subscription_id: fd075559-43fc-4fbe-8dee-21e125a9dafc
  valid_vm_sizes:
    - Standard_DS1_v2
    - Standard_D2s_v3
    - Standard_D4s_v3
    - Standard_D8s_v3
    - Standard_D16s_v3
deployments:
  azure:
    andaime-rg: []
    andaime-rg-20240818101448:
      - name: f5ii4k-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: cwz57b-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: 50v7xj-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: zbq59h-vm
        orchestrator: false
        privateip: ""
        publicip: ""
    andaime-rg-20240818101706:
      - name: h56ljx-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: al0ifv-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: lxlnju-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: vp71q3-vm
        orchestrator: false
        privateip: ""
        publicip: ""
    andaime-rg-20240818101834:
      - name: ah7dwa-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: 8gu15t-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: v88o8l-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: ixqr9q-vm
        orchestrator: false
        privateip: ""
        publicip: ""
    andaime-rg-20240818102118:
      - name: roa73i-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: f60a71-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: rqok24-vm
        orchestrator: false
        privateip: ""
        publicip: ""
      - name: yksh51-vm
        orchestrator: false
        privateip: ""
        publicip: ""
    andaime-rg-20240818102334:
      - Name: va970o-vm
        Orchestrator: false
        PrivateIP: ""
        PublicIP: ""
      - Name: maah08-vm
        Orchestrator: false
        PrivateIP: ""
        PublicIP: ""
      - Name: ggi909-vm
        Orchestrator: false
        PrivateIP: ""
        PublicIP: ""
      - Name: 34wfg1-vm
        Orchestrator: false
        PrivateIP: ""
        PublicIP: ""
general:
  log_level: info
  log_path: /tmp/andaime.log
  project_id: andaime-project
  ssh_port: 22
  ssh_private_key_path: /Users/daaronch/.ssh/id_rsa
  ssh_public_key_path: /Users/daaronch/.ssh/id_rsa.pub
  ssh_user: azureuser
