azure:
  allowed_ports:
    - 22
    - 80
    - 443
  disk_size_gb: 30
  default_machine_type: Standard_DS1_v2
  default_count_per_zone: 1
  machines:
    - location: eastus
      parameters:
        - count: 2
          type: Standard_DS1_v2
    - location: westus
    - location: centralus
      parameters:
        - count: 1
          type: Standard_DS1_v2
          orchestrator: True
    - location: eastus2
    - location: southcentralus
    - location: southcentralus
    - location: westeurope
    - location: uksouth
    - location: eastasia
    - location: southeastasia
    - location: westus2
  resource_group_name: andaime-rg
  subscription_id: fd075559-43fc-4fbe-8dee-21e125a9dafc
general:
  project_id: andaime-project
  ssh_public_key_path: ~/.ssh/id_rsa.pub
  ssh_private_key_path: ~/.ssh/id_rsa
