aws:
  regions:
    - us-west-2
    - us-east-1
    - eu-west-1
    - ap-southeast-1
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-west-2


        - location: eastus
          parameters:
            count: 2
            type: Standard_DS1_v2
        - location: centralus
          parameters:
            count: 1
            orchestrator: true
            type: Standard_DS1_v2
        - location: eastus2