azure:
  allowed_ports:
    - 22
  default_count_per_zone: 1
  default_disk_size_gb: 30
  default_location: eastus2
  default_machine_type: Standard_DS4_v2
  default_vm_size: Standard_B2s
  disk_size_gb: 30
  machines:
    - location: eastus2
      parameters:
        count: 2
        type: Standard_DS4_v2
    - location: westus
      parameters:
        count: 4
    - location: brazilsouth
      parameters:
        type: Standard_D2as_v4
    - location: japaneast
      parameters:
        orchestrator: true
    - location: uaenorth
      parameters:
        type: Standard_D2as_v4
  resource_group_location: eastus2
  resource_group_name: andaime-rg
  resource_prefix: andaime
  subscription_id: fd075559-43fc-4fbe-8dee-21e125a9dafc
  valid_vm_sizes:
    - Standard_DS1_v2
    - Standard_DS2_v2
    - Standard_DS3_v2
    - Standard_DS4_v2
    - Standard_D2s_v3
    - Standard_D4s_v3
    - Standard_D8s_v3
    - Standard_D16s_v3
general:
  log_level: info
  log_path: /tmp/andaime.log
  project_prefix: andaime
  ssh_port: 22
  ssh_private_key_path: /Users/daaronch/.ssh/id_rsa
  ssh_public_key_path: /Users/daaronch/.ssh/id_rsa.pub
  ssh_user: azureuser
