version: "0.2"
ignorePaths:
  - "**/**"
  - "!cmd/**"
  - "!internal/**"
  - "!pkg/**"
  - "!**/**/*.md"
dictionaryDefinitions: []
dictionaries: ["./.cspell/project-dictionary.txt"]
ignoreWords: []
import: []
