version: "0.2"
ignorePaths:
  - ".git/**"
  - ".github/**"
  - ".vscode/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/tmp/**"
  - "**/temp/**"
  - "**/logs/**"
  - "**/coverage/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/vendor/**"
  - "!cmd/**"
  - "!internal/**"
  - "!pkg/**"
  - "!**/*.md"
dictionaryDefinitions: []
dictionaries: ["./.cspell/project-dictionary.txt"]
ignoreWords: []
import: []
