// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	ssh "golang.org/x/crypto/ssh"

	sshutils "github.com/bacalhau-project/andaime/pkg/models/interfaces/sshutils"
)

// MockSFTPClientCreator is an autogenerated mock type for the SFTPClientCreator type
type MockSFTPClientCreator struct {
	mock.Mock
}

type MockSFTPClientCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSFTPClientCreator) EXPECT() *MockSFTPClientCreator_Expecter {
	return &MockSFTPClientCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: client
func (_m *MockSFTPClientCreator) Execute(client *ssh.Client) (sshutils.SFTPClienter, error) {
	ret := _m.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 sshutils.SFTPClienter
	var r1 error
	if rf, ok := ret.Get(0).(func(*ssh.Client) (sshutils.SFTPClienter, error)); ok {
		return rf(client)
	}
	if rf, ok := ret.Get(0).(func(*ssh.Client) sshutils.SFTPClienter); ok {
		r0 = rf(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sshutils.SFTPClienter)
		}
	}

	if rf, ok := ret.Get(1).(func(*ssh.Client) error); ok {
		r1 = rf(client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSFTPClientCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSFTPClientCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - client *ssh.Client
func (_e *MockSFTPClientCreator_Expecter) Execute(client interface{}) *MockSFTPClientCreator_Execute_Call {
	return &MockSFTPClientCreator_Execute_Call{Call: _e.mock.On("Execute", client)}
}

func (_c *MockSFTPClientCreator_Execute_Call) Run(run func(client *ssh.Client)) *MockSFTPClientCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ssh.Client))
	})
	return _c
}

func (_c *MockSFTPClientCreator_Execute_Call) Return(_a0 sshutils.SFTPClienter, _a1 error) *MockSFTPClientCreator_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSFTPClientCreator_Execute_Call) RunAndReturn(run func(*ssh.Client) (sshutils.SFTPClienter, error)) *MockSFTPClientCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSFTPClientCreator creates a new instance of MockSFTPClientCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSFTPClientCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSFTPClientCreator {
	mock := &MockSFTPClientCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
