// Code generated by mockery v2.50.1. DO NOT EDIT.

package sshutils

import mock "github.com/stretchr/testify/mock"

// MockSFTPFile is an autogenerated mock type for the SFTPFile type
type MockSFTPFile struct {
	mock.Mock
}

type MockSFTPFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSFTPFile) EXPECT() *MockSFTPFile_Expecter {
	return &MockSFTPFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockSFTPFile) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSFTPFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSFTPFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSFTPFile_Expecter) Close() *MockSFTPFile_Close_Call {
	return &MockSFTPFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSFTPFile_Close_Call) Run(run func()) *MockSFTPFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSFTPFile_Close_Call) Return(_a0 error) *MockSFTPFile_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSFTPFile_Close_Call) RunAndReturn(run func() error) *MockSFTPFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *MockSFTPFile) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSFTPFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockSFTPFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockSFTPFile_Expecter) Write(p interface{}) *MockSFTPFile_Write_Call {
	return &MockSFTPFile_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockSFTPFile_Write_Call) Run(run func(p []byte)) *MockSFTPFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockSFTPFile_Write_Call) Return(n int, err error) *MockSFTPFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSFTPFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockSFTPFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSFTPFile creates a new instance of MockSFTPFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSFTPFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSFTPFile {
	mock := &MockSFTPFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
