// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	awsprovider "github.com/bacalhau-project/andaime/pkg/providers/aws"

	mock "github.com/stretchr/testify/mock"
)

// MockAWSProviderFunc is an autogenerated mock type for the AWSProviderFunc type
type MockAWSProviderFunc struct {
	mock.Mock
}

type MockAWSProviderFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWSProviderFunc) EXPECT() *MockAWSProviderFunc_Expecter {
	return &MockAWSProviderFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockAWSProviderFunc) Execute(ctx context.Context) (awsprovider.AWSProviderer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 awsprovider.AWSProviderer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (awsprovider.AWSProviderer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) awsprovider.AWSProviderer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(awsprovider.AWSProviderer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAWSProviderFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAWSProviderFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAWSProviderFunc_Expecter) Execute(ctx interface{}) *MockAWSProviderFunc_Execute_Call {
	return &MockAWSProviderFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockAWSProviderFunc_Execute_Call) Run(run func(ctx context.Context)) *MockAWSProviderFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAWSProviderFunc_Execute_Call) Return(_a0 awsprovider.AWSProviderer, _a1 error) *MockAWSProviderFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAWSProviderFunc_Execute_Call) RunAndReturn(run func(context.Context) (awsprovider.AWSProviderer, error)) *MockAWSProviderFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAWSProviderFunc creates a new instance of MockAWSProviderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWSProviderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWSProviderFunc {
	mock := &MockAWSProviderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
