// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockConfigInterfacer is an autogenerated mock type for the ConfigInterfacer type
type MockConfigInterfacer struct {
	mock.Mock
}

type MockConfigInterfacer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigInterfacer) EXPECT() *MockConfigInterfacer_Expecter {
	return &MockConfigInterfacer_Expecter{mock: &_m.Mock}
}

// GetString provides a mock function with given fields: key
func (_m *MockConfigInterfacer) GetString(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigInterfacer_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockConfigInterfacer_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - key string
func (_e *MockConfigInterfacer_Expecter) GetString(key interface{}) *MockConfigInterfacer_GetString_Call {
	return &MockConfigInterfacer_GetString_Call{Call: _e.mock.On("GetString", key)}
}

func (_c *MockConfigInterfacer_GetString_Call) Run(run func(key string)) *MockConfigInterfacer_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigInterfacer_GetString_Call) Return(_a0 string) *MockConfigInterfacer_GetString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigInterfacer_GetString_Call) RunAndReturn(run func(string) string) *MockConfigInterfacer_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigInterfacer creates a new instance of MockConfigInterfacer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigInterfacer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigInterfacer {
	mock := &MockConfigInterfacer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
