// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/bacalhau-project/andaime/pkg/providers/common"

	mock "github.com/stretchr/testify/mock"
)

// MockProviderFactory is an autogenerated mock type for the ProviderFactory type
type MockProviderFactory struct {
	mock.Mock
}

type MockProviderFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderFactory) EXPECT() *MockProviderFactory_Expecter {
	return &MockProviderFactory_Expecter{mock: &_m.Mock}
}

// CreateProvider provides a mock function with given fields: ctx
func (_m *MockProviderFactory) CreateProvider(ctx context.Context) (common.Providerer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateProvider")
	}

	var r0 common.Providerer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (common.Providerer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) common.Providerer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Providerer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderFactory_CreateProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProvider'
type MockProviderFactory_CreateProvider_Call struct {
	*mock.Call
}

// CreateProvider is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProviderFactory_Expecter) CreateProvider(ctx interface{}) *MockProviderFactory_CreateProvider_Call {
	return &MockProviderFactory_CreateProvider_Call{Call: _e.mock.On("CreateProvider", ctx)}
}

func (_c *MockProviderFactory_CreateProvider_Call) Run(run func(ctx context.Context)) *MockProviderFactory_CreateProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProviderFactory_CreateProvider_Call) Return(_a0 common.Providerer, _a1 error) *MockProviderFactory_CreateProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderFactory_CreateProvider_Call) RunAndReturn(run func(context.Context) (common.Providerer, error)) *MockProviderFactory_CreateProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderFactory creates a new instance of MockProviderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderFactory {
	mock := &MockProviderFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
