// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/bacalhau-project/andaime/pkg/providers/common"

	mock "github.com/stretchr/testify/mock"
)

// MockFactoryFunc is an autogenerated mock type for the FactoryFunc type
type MockFactoryFunc struct {
	mock.Mock
}

type MockFactoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactoryFunc) EXPECT() *MockFactoryFunc_Expecter {
	return &MockFactoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockFactoryFunc) Execute(ctx context.Context) (common.Providerer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 common.Providerer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (common.Providerer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) common.Providerer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Providerer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFactoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFactoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFactoryFunc_Expecter) Execute(ctx interface{}) *MockFactoryFunc_Execute_Call {
	return &MockFactoryFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockFactoryFunc_Execute_Call) Run(run func(ctx context.Context)) *MockFactoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFactoryFunc_Execute_Call) Return(_a0 common.Providerer, _a1 error) *MockFactoryFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFactoryFunc_Execute_Call) RunAndReturn(run func(context.Context) (common.Providerer, error)) *MockFactoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFactoryFunc creates a new instance of MockFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactoryFunc {
	mock := &MockFactoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
