// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPollerer is an autogenerated mock type for the Pollerer type
type MockPollerer struct {
	mock.Mock
}

type MockPollerer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPollerer) EXPECT() *MockPollerer_Expecter {
	return &MockPollerer_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function with given fields: ctx
func (_m *MockPollerer) Poll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPollerer_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockPollerer_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPollerer_Expecter) Poll(ctx interface{}) *MockPollerer_Poll_Call {
	return &MockPollerer_Poll_Call{Call: _e.mock.On("Poll", ctx)}
}

func (_c *MockPollerer_Poll_Call) Run(run func(ctx context.Context)) *MockPollerer_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPollerer_Poll_Call) Return(_a0 error) *MockPollerer_Poll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPollerer_Poll_Call) RunAndReturn(run func(context.Context) error) *MockPollerer_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPollerer creates a new instance of MockPollerer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPollerer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPollerer {
	mock := &MockPollerer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
