package internal

import "strings"

func IsValidBacalhauKey(key string) bool {
	allKeys := strings.Split(allKeysString14, "\n")
	for _, k := range allKeys {
		if k == key {
			return true
		}
	}
	return false
}

// Generated with bacalhau config list --output json | jq -r '.[].Key'

const allKeysString14 = `
auth.accesspolicypath
auth.methods
auth.tokenspath
metrics.eventtracerpath
node.allowlistedlocalpaths
node.clientapi.clienttls.cacert
node.clientapi.clienttls.insecure
node.clientapi.clienttls.usetls
node.clientapi.host
node.clientapi.port
node.clientapi.tls.autocert
node.clientapi.tls.autocertcachepath
node.clientapi.tls.selfsigned
node.clientapi.tls.servercertificate
node.clientapi.tls.serverkey
node.compute.capacity.defaultjobresourcelimits.cpu
node.compute.capacity.defaultjobresourcelimits.disk
node.compute.capacity.defaultjobresourcelimits.gpu
node.compute.capacity.defaultjobresourcelimits.memory
node.compute.capacity.ignorephysicalresourcelimits
node.compute.capacity.jobresourcelimits.cpu
node.compute.capacity.jobresourcelimits.disk
node.compute.capacity.jobresourcelimits.gpu
node.compute.capacity.jobresourcelimits.memory
node.compute.capacity.totalresourcelimits.cpu
node.compute.capacity.totalresourcelimits.disk
node.compute.capacity.totalresourcelimits.gpu
node.compute.capacity.totalresourcelimits.memory
node.compute.controlplanesettings.heartbeatfrequency
node.compute.controlplanesettings.heartbeattopic
node.compute.controlplanesettings.infoupdatefrequency
node.compute.controlplanesettings.resourceupdatefrequency
node.compute.executionstore.path
node.compute.executionstore.type
node.compute.jobselection.acceptnetworkedjobs
node.compute.jobselection.locality
node.compute.jobselection.probeexec
node.compute.jobselection.probehttp
node.compute.jobselection.rejectstatelessjobs
node.compute.jobtimeouts.defaultjobexecutiontimeout
node.compute.jobtimeouts.jobexecutiontimeoutclientidbypasslist
node.compute.jobtimeouts.jobnegotiationtimeout
node.compute.jobtimeouts.maxjobexecutiontimeout
node.compute.jobtimeouts.minjobexecutiontimeout
node.compute.localpublisher.address
node.compute.localpublisher.directory
node.compute.localpublisher.port
node.compute.logging.logrunningexecutionsinterval
node.compute.logstreamconfig.channelbuffersize
node.compute.manifestcache.duration
node.compute.manifestcache.frequency
node.compute.manifestcache.size
node.computestoragepath
node.disabledfeatures.engines
node.disabledfeatures.publishers
node.disabledfeatures.storages
node.downloadurlrequestretries
node.downloadurlrequesttimeout
node.executorpluginpath
node.ipfs.connect
node.labels
node.loggingmode
node.name
node.nameprovider
node.network.advertisedaddress
node.network.authsecret
node.network.cluster.advertisedaddress
node.network.cluster.name
node.network.cluster.peers
node.network.cluster.port
node.network.orchestrators
node.network.port
node.network.storedir
node.requester.controlplanesettings.heartbeatcheckfrequency
node.requester.controlplanesettings.heartbeattopic
node.requester.controlplanesettings.nodedisconnectedafter
node.requester.defaultpublisher
node.requester.evaluationbroker.evalbrokerinitialretrydelay
node.requester.evaluationbroker.evalbrokermaxretrycount
node.requester.evaluationbroker.evalbrokersubsequentretrydelay
node.requester.evaluationbroker.evalbrokervisibilitytimeout
node.requester.externalverifierhook
node.requester.failureinjectionconfig.isbadactor
node.requester.housekeepingbackgroundtaskinterval
node.requester.jobdefaults.executiontimeout
node.requester.jobdefaults.queuetimeout
node.requester.jobdefaults.totaltimeout
node.requester.jobselectionpolicy.acceptnetworkedjobs
node.requester.jobselectionpolicy.locality
node.requester.jobselectionpolicy.probeexec
node.requester.jobselectionpolicy.probehttp
node.requester.jobselectionpolicy.rejectstatelessjobs
node.requester.jobstore.path
node.requester.jobstore.type
node.requester.manualnodeapproval
node.requester.nodeinfostorettl
node.requester.noderankrandomnessrange
node.requester.overaskforbidsfactor
node.requester.scheduler.nodeoversubscriptionfactor
node.requester.scheduler.queuebackoff
node.requester.storageprovider.s3.presignedurldisabled
node.requester.storageprovider.s3.presignedurlexpiration
node.requester.tagcache.duration
node.requester.tagcache.frequency
node.requester.tagcache.size
node.requester.translationenabled
node.requester.worker.workercount
node.requester.worker.workerevaldequeuebasebackoff
node.requester.worker.workerevaldequeuemaxbackoff
node.requester.worker.workerevaldequeuetimeout
node.serverapi.clienttls.cacert
node.serverapi.clienttls.insecure
node.serverapi.clienttls.usetls
node.serverapi.host
node.serverapi.port
node.serverapi.tls.autocert
node.serverapi.tls.autocertcachepath
node.serverapi.tls.selfsigned
node.serverapi.tls.servercertificate
node.serverapi.tls.serverkey
node.strictversionmatch
node.type
node.volumesizerequesttimeout
node.webui.enabled
node.webui.port
update.checkfrequency
update.checkstatepath
update.skipchecks
user.installationid
user.keypath
`

//nolint:unused
const allKeysString15 = `
api.auth.accesspolicypath
api.auth.methods
api.host
api.port
api.tls.autocert
api.tls.autocertcachepath
api.tls.cafile
api.tls.certfile
api.tls.insecure
api.tls.keyfile
api.tls.selfsigned
api.tls.usetls
compute.allocatedcapacity.cpu
compute.allocatedcapacity.disk
compute.allocatedcapacity.gpu
compute.allocatedcapacity.memory
compute.allowlistedlocalpaths
compute.enabled
compute.heartbeat.infoupdateinterval
compute.heartbeat.interval
compute.heartbeat.resourceupdateinterval
compute.labels
compute.orchestrators
compute.tls.autocert
compute.tls.autocertcachepath
compute.tls.cafile
compute.tls.certfile
compute.tls.insecure
compute.tls.keyfile
compute.tls.selfsigned
compute.tls.usetls
datadir
disableanalytics
engines.disabled
engines.types.docker.manifestcache.refresh
engines.types.docker.manifestcache.size
engines.types.docker.manifestcache.ttl
featureflags.exectranslation
inputsources.disabled
inputsources.maxretrycount
inputsources.readtimeout
inputsources.types.ipfs.endpoint
inputsources.types.s3.accesskey
inputsources.types.s3.endpoint
inputsources.types.s3.secretkey
jobadmissioncontrol.acceptnetworkedjobs
jobadmissioncontrol.probeexec
jobadmissioncontrol.probehttp
jobadmissioncontrol.rejectstatelessjobs
jobdefaults.batch.priority
jobdefaults.batch.task.publisher.config.params
jobdefaults.batch.task.publisher.config.type
jobdefaults.batch.task.resources.cpu
jobdefaults.batch.task.resources.disk
jobdefaults.batch.task.resources.gpu
jobdefaults.batch.task.resources.memory
jobdefaults.batch.task.timeouts.executiontimeout
jobdefaults.batch.task.timeouts.totaltimeout
jobdefaults.daemon.priority
jobdefaults.daemon.task.resources.cpu
jobdefaults.daemon.task.resources.disk
jobdefaults.daemon.task.resources.gpu
jobdefaults.daemon.task.resources.memory
jobdefaults.ops.priority
jobdefaults.ops.task.publisher.config.params
jobdefaults.ops.task.publisher.config.type
jobdefaults.ops.task.resources.cpu
jobdefaults.ops.task.resources.disk
jobdefaults.ops.task.resources.gpu
jobdefaults.ops.task.resources.memory
jobdefaults.ops.task.timeouts.executiontimeout
jobdefaults.ops.task.timeouts.totaltimeout
jobdefaults.service.priority
jobdefaults.service.task.resources.cpu
jobdefaults.service.task.resources.disk
jobdefaults.service.task.resources.gpu
jobdefaults.service.task.resources.memory
logging.level
logging.logdebuginfointerval
logging.mode
nameprovider
orchestrator.advertise
orchestrator.authsecret
orchestrator.cluster.advertise
orchestrator.cluster.host
orchestrator.cluster.name
orchestrator.cluster.peers
orchestrator.cluster.port
orchestrator.enabled
orchestrator.evaluationbroker.maxretrycount
orchestrator.evaluationbroker.visibilitytimeout
orchestrator.host
orchestrator.nodemanager.disconnecttimeout
orchestrator.nodemanager.manualapproval
orchestrator.port
orchestrator.scheduler.housekeepinginterval
orchestrator.scheduler.housekeepingtimeout
orchestrator.scheduler.workercount
orchestrator.tls.autocert
orchestrator.tls.autocertcachepath
orchestrator.tls.cafile
orchestrator.tls.certfile
orchestrator.tls.insecure
orchestrator.tls.keyfile
orchestrator.tls.selfsigned
orchestrator.tls.usetls
publishers.disabled
publishers.types.ipfs.endpoint
publishers.types.local.address
publishers.types.local.directory
publishers.types.local.port
publishers.types.s3.presignedurldisabled
publishers.types.s3.presignedurlexpiration
resultdownloaders.disabled
resultdownloaders.timeout
resultdownloaders.types.ipfs.endpoint
strictversionmatch
updateconfig.interval
webui.enabled
webui.listen
`
